import fs from 'node:fs';
import path from 'node:path';

/**
 * Генерирует реестр `label -> SVG-компонент` из `../shared/signs/images/*.svg`.
 * Нужно, чтобы Metro точно забандлил все SVG, и мы могли выбирать иконку по label.
 */

const appDir = path.resolve(import.meta.dirname, '..');
const sharedImagesDir = path.resolve(appDir, '..', 'shared', 'signs', 'images');
const outFile = path.resolve(appDir, 'src', 'signs', 'signRegistry.tsx');

function isSvg(name) {
  return name.toLowerCase().endsWith('.svg');
}

function toLabel(fileName) {
  return fileName.replace(/\.svg$/i, '');
}

function toIdent(label) {
  const safe = label.replace(/[^a-zA-Z0-9_]+/g, '_');
  return `Sign_${safe}`;
}

if (!fs.existsSync(sharedImagesDir)) {
  console.error(`[generateSignRegistry] Folder not found: ${sharedImagesDir}`);
  process.exit(1);
}

const files = fs
  .readdirSync(sharedImagesDir)
  .filter(isSvg)
  .sort((a, b) => a.localeCompare(b));

const imports = [];
const entries = [];

for (const file of files) {
  const label = toLabel(file);
  const ident = toIdent(label);
  const relImport = `../../../shared/signs/images/${file}`;
  imports.push(`import ${ident} from '${relImport}';`);
  entries.push(`  '${label}': ${ident},`);
}

const content = `// AUTO-GENERATED by scripts/generateSignRegistry.mjs
// DO NOT EDIT MANUALLY.

import type * as React from 'react';
import type { SvgProps } from 'react-native-svg';

${imports.join('\n')}

export type SignComponent = React.FC<SvgProps>;

export const signByLabel: Record<string, SignComponent> = {
${entries.join('\n')}
};
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, content, 'utf8');
console.log(`[generateSignRegistry] Wrote ${outFile} (${files.length} signs)`);

